- name: Install Paru AUR helper for Arch Linux
  become: true
  block:
    - name: Check if paru is already installed
      ansible.builtin.command: command -v paru
      register: paru_exists
      failed_when: false
      changed_when: false

    - name: Install paru if not already present
      when: paru_exists.rc != 0
      block:
        - name: Install dependencies to build packages
          community.general.pacman:
            name:
              - base-devel
              - git
            state: present
            update_cache: yes

        - name: Clone the paru-bin repo from AUR
          ansible.builtin.git:
            repo: https://aur.archlinux.org/paru-bin.git
            dest: /tmp/paru-bin
          become: true

        - name: Build the paru package
          ansible.builtin.command: makepkg -si --noconfirm
          args:
            chdir: /tmp/paru-bin
            creates: /usr/bin/paru
          become: false

- name: Install AUR packages with paru
  become: false
  block:
    - name: Install Google Chrome from AUR
      ansible.builtin.command: paru -S --noconfirm google-chrome
      args:
        creates: /usr/bin/google-chrome-stable
      changed_when: true
